DrinkAndGo/ViewModels/DrinkListViewModel.cs
using DrinkAndGo.Data.Models;
using System.Collections.Generic;

namespace DrinkAndGo.ViewModels
{
    public class DrinkListViewModel
    {
        public IEnumerable<Drink> Drinks { get; set; }
        public string CurrentCategory { get; set; }
    }
}

DrinkAndGo/ViewModels/HomeViewModel.cs
using DrinkAndGo.Data.Models;
using System.Collections.Generic;

namespace DrinkAndGo.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Drink> PreferredDrinks { get; set; }

    }
}

DrinkAndGo/ViewModels/ShoppingCartViewModel.cs
using DrinkAndGo.Data.Models;

namespace DrinkAndGo.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShopingCart ShopingCart { get; set; }
        public decimal ShoppingCartTotal { get; set; }
    }
}

DrinkAndGo/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DrinkAndGo.Controllers
{
    public class ContactController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }
    }
}

DrinkAndGo/Controllers/DrinkController.cs
using DrinkAndGo.Data.Models;
using DrinkAndGo.Data.Models.Interfaces;
using DrinkAndGo.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace DrinkAndGo.Controllers
{
    public class DrinkController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IDrinkRepository _drinkRepository;
        public DrinkController(ICategoryRepository categoryRepository, IDrinkRepository drinkRepository)
        {
            _drinkRepository = drinkRepository;
            _categoryRepository = categoryRepository;
        }
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Drink> drinks;

            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                drinks = _drinkRepository.Drinks.OrderBy(n => n.DrinkId);
                currentCategory = "All drinks";
            }
            else
            {
                if (string.Equals("Alcoholic", _category, StringComparison.OrdinalIgnoreCase))
                {
                    drinks = _drinkRepository.Drinks.Where(p => p.Category.CategoryName.Equals("Alcoholic"));
                }
                else
                {
                    drinks = _drinkRepository.Drinks.Where(p => p.Category.CategoryName.Equals("Non-alcoholic"));
                }

                currentCategory = _category;
            }

            var drinkListViewModel = new DrinkListViewModel
            {
                Drinks = drinks,
                CurrentCategory = currentCategory
            };

            return View(drinkListViewModel);
        }
    }
}

DrinkAndGo/Controllers/HomeController.cs
using DrinkAndGo.Data.Models.Interfaces;
using DrinkAndGo.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DrinkAndGo.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDrinkRepository drinkRepository;

        public HomeController(IDrinkRepository drinkRepository)
        {
            this.drinkRepository = drinkRepository;
        }
        public IActionResult Index()
        {
            var hVM = new HomeViewModel
            {
                PreferredDrinks = drinkRepository.PreferedDrink

            };
            return View(hVM);
        }
    }
}

DrinkAndGo/Controllers/OrderController.cs
using DrinkAndGo.Data.Interfaces;
using DrinkAndGo.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace DrinkAndGo.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShopingCart _shoppingCart;

        public OrderController(IOrderRepository orderRepository, ShopingCart shoppingCart)
        {
            _orderRepository = orderRepository ??
                throw new ArgumentNullException(nameof(orderRepository));
            _shoppingCart = shoppingCart ??
                throw new ArgumentNullException(nameof(shoppingCart));
        }

        [Authorize]
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Checkout(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            if(_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your card is empty, add some drinks first.");
            }

            if(ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }

            return View(order);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order!";
            return View();
        }
    }
}

DrinkAndGo/Controllers/ShoppingCartController.cs
using DrinkAndGo.Data;
using DrinkAndGo.Data.Models;
using DrinkAndGo.Data.Models.Interfaces;
using DrinkAndGo.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DrinkAndGo.Controllers
{
    public class ShoppingCartController : Controller
    {
       
        private readonly ShopingCart _shopingCart;
        private readonly IDrinkRepository _drinkRepository;

        public ShoppingCartController(ShopingCart shopingCart, IDrinkRepository drinkRepository)
        {
           _shopingCart = shopingCart;
           _drinkRepository = drinkRepository;           
        } 
        public IActionResult Index()
        {
            var items= _shopingCart.GetShoppingCartItems();
            _shopingCart.ShoppingCartItems=items;
            var sCVM = new ShoppingCartViewModel
            {
                ShopingCart = _shopingCart,
                ShoppingCartTotal = _shopingCart.GetShoppingCartTotal(),
            };
            return View(sCVM);
        }
        public RedirectToActionResult AddToShoppingCart(int drinkId)
        {
            var selectedDrink=_drinkRepository.Drinks.FirstOrDefault(p => p.DrinkId == drinkId);
            if (selectedDrink != null)
            {
                _shopingCart.AddToCart(selectedDrink, 1);
            }
            return RedirectToAction("Index");

        }
        public RedirectToActionResult RemoveFromShoppingCart(int drinkId)
        {
            var selectedDrink = _drinkRepository.Drinks.FirstOrDefault(p => p.DrinkId == drinkId);
            if (selectedDrink != null)
            {
                _shopingCart.RemoveFromCart(selectedDrink);
            }
            return RedirectToAction("Index");
        }
    }
}

DrinkAndGo/Views/Contact/Index.cshtml
@{ 
    ViewData["Title"] = "Contact Us";
}

<div class="text-center">
    <h1>Contact us</h1>
    <p>If you have any questions please do not hesitate contact us:</p>

    <email address="Mhmdhmooda44@gmail.com" content="Email Us"></email>
</div>

DrinkAndGo/Views/Drink/Details.cshtml
@model Drink

@{ 
    ViewData["Title"] = "Details";
}

<h2>@Model.Name</h2>

<div class="thumbnail">
    <img src="@Model.ImageUrl" />
    <div class="caption-full">
        <h3 class="pull-right">@Model.Price</h3>
        <h3>
            <a href="#">@Model.Name</a>
        </h3>
        <h4>@Model.ShortDescription</h4>
        <p>@Model.LongDescription</p>
        <div class="addToCart">
            <a class="btn btn-primary"
               asp-controller="ShoppingCart"
               asp-action="AddToShoppingCart"
               asp-route-drinkId="@Model.DrinkId">Add to cart</a>
        </div>
    </div>
</div>

DrinkAndGo/Views/Drink/List.cshtml
@model DrinkListViewModel

@{
    ViewData["Title"] = "Drinks";
}

<div class="text-center">
    <div>
        <h2>All drinks are shown here</h2>
    </div>


    <h2>@Model.CurrentCategory</h2>
</div>


@foreach (var drink in Model.Drinks)
{
    <partial name="_DrinksSummary" model="drink" />
}

DrinkAndGo/Views/Home/Index.cshtml
@model HomeViewModel


@{
    ViewData["Title"] = "Home";
}


<div class="container">

    <partial name="_Carousel" />

    <h2>Prefered drinks of the week</h2>
    <h4>Clients preferences - just for you!</h4>


    @foreach (var drink in Model.PreferredDrinks)
    {
        <partial name="_DrinksSummary" model="drink" />
    }


</div>

DrinkAndGo/Views/Order/Checkout.cshtml
@model Order

<div class="row orderForm ">
    <h3 class="text-center">You are just one step away from ordering your drinks.</h3>

    <div asp-validation-summary="All"></div>

    <form asp-action="Checkout" method="post" class="form-horizontal" role="form">

        <div class="form-group">
            <label asp-for="FirstName" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="LastName" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="AddressLine1" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="AddressLine1" class="form-control" />
                <span asp-validation-for="AddressLine1" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="AddressLine2" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="AddressLine2" class="form-control" />
                <span asp-validation-for="AddressLine2" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="ZipCode" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="State" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Country" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="PhoneNumber" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="btn-group col-md-offset-2 col-md-8">
                <input class="btn btn-success" type="submit" value="Complete order" />
            </div>
        </div>

    </form>
</div>

DrinkAndGo/Views/Order/CheckoutComplete.cshtml
@{ 
    ViewData["Title"] = "Order complete";
}

<h1>
    @ViewBag.CheckoutCompleteMessage
</h1>

DrinkAndGo/Views/Shared/Components/CategoryMenu/Default.cshtml
<li class="dropdown">
    <a asp-controller="Drink"
       asp-action="Index"
       class="dropdown-toggle" data-toggle="dropdown">Drinks<b class="caret"></b></a>
    <ul class="dropdown-menu">
        @foreach (var category in Model)
        {
            <li>
                <a asp-controller="Drink" asp-action="List"
                   asp-route-category="@category.CategoryName">@category.CategoryName</a>
            </li>
        }
        <li class="divider"></li>
        <li>
            <a asp-controller="Drink" asp-action="List" asp-route-category="">View all drinks</a>
        </li>
    </ul>
</li>

DrinkAndGo/Views/Shared/Components/ShoppingCartSummary/Default.cshtml
@model ShoppingCartViewModel

@if (Model.ShopingCart.ShoppingCartItems.Count > 0)
{
    <li>
        <a asp-controller="ShoppingCart" style="pointer-events: none;">
            <span class="glyphicon glyphicon-shopping-cart"></span>
            <span id="cart-status">
                @Model.ShopingCart.ShoppingCartItems.Count
            </span>
        </a>
    </li>
}

DrinkAndGo/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder marginTop1">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

DrinkAndGo/Views/Shared/_DrinksSummary.cshtml
@model Drink

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" style="min-height:300px;width:95%;" class="img-responsive" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Drink" asp-action="Details" asp-route-id="@Model.DrinkId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
    </div>
    <div class="addToCart text-right">
        <p class="button">
            <a class="btn btn-success" id="cartButton"
               asp-controller="ShoppingCart"
               asp-action="AddToShoppingCart"
               asp-route-drinkId="@Model.DrinkId">
                Add To Cart
            </a>
        </p>
    </div>
</div>

DrinkAndGo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet" type="text/css" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li><a asp-controller="Contact" asp-action="Index">Contact Us</a></li>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>

                <ul class="text-left">
                    <li>@await Html.PartialAsync("_LoginPartial")</li>
                </ul>

            </div>
        </div>
    </nav>

    <div class="container">
        <div>
            @RenderBody()
        </div>

    </div>

    <hr />

    <footer class="border-top footer text-muted">
        <div class="container">
            All rights reserved &copy; @DateTime.UtcNow.Year <a href="https://github.com/mahmmoudkinawy" target="_blank"> Kinawy's GitHub </a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

DrinkAndGo/Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel

@{ 
    ViewData["Title"] = "Shopping Cart";
}

<div class="container">

    <div class="row checkoutForm">
        <h2>Your shopping cart</h2>
        <h4>Here are the drinks in your shopping cart.</h4>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Selected amount</th>
                    <th>Drink</th>
                    <th class="text-right">Price</th>
                    <th class="text-right">Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var line in Model.ShopingCart.ShoppingCartItems)
                {
                    <tr>
                        <td class="text-center">@line.Amount</td>
                        <td class="text-left">@line.Drink.Name</td>
                        <td class="text-right">@line.Drink.Price.ToString("c")</td>
                        <td class="text-right">
                            @((line.Amount * line.Drink.Price).ToString("c"))
                        </td>
                        <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-drinkId="@line.Drink.DrinkId"></a></td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Total:</td>
                    <td class="text-right">
                        @Model.ShoppingCartTotal.ToString("c")
                    </td>
                </tr>
            </tfoot>
        </table>

        <div class="text-right">
            <div class="btn-group ">
                <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
                <a class="btn-group">
                    <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        Add more drinks<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a asp-controller="Drink" asp-action="List" asp-route-category="Alcoholic">Alcoholic</a></li>
                        <li><a asp-controller="Drink" asp-action="List" asp-route-category="Non-alcoholic">Non Alcoholic</a></li>
                    </ul>
                </a>
            </div>
        </div>
    </div>
</div>